export const INDIAN_STATES = [
  "All India",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Puducherry",
  "Chandigarh"
];

export const EXAM_SECTORS = [
  "Central Government",
  "State Government",
  "UPSC",
  "SSC",
  "State PSC",
  "Railway",
  "Clerical",
  "Banking",
  "Insurance",
  "Defence",
  "Police",
  "Paramilitary",
  "PSU",
  "Teaching",
  "Engineering",
  "Medical",
  "Nursing",
  "Pharmacy",
  "Judiciary",
  "Forest Department",
  "Post Office",
  "Data Entry",
  "Apprentice",
  "Research",
  "Public Service Commissions"
];

export const EDUCATION_QUALIFICATIONS = [
  "8th Pass",
  "10th Pass",
  "12th Pass",
  "Graduate",
  "Postgraduate",
  "Diploma / ITI",
  "Engineering Graduate (BTech/BE)",
  "Medical/Nursing/Pharmacy",
  "Teaching Qualified (BEd/TET)"
];
