export const INDIAN_STATES = [
  "All India",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Puducherry",
  "Chandigarh"
];

export const EXAM_SECTORS = [
  "UPSC",
  "SSC",
  "Railway",
  "Banking",
  "Defence",
  "Police",
  "State Government",
  "PSU",
  "Teaching",
  "Engineering (AE/JE)",
  "Medical",
  "Judiciary",
  "Paramilitary",
  "Forest Department",
  "Post Office",
  "Insurance",
  "Public Service Commissions"
];
