INSERT INTO jobs (title, department, location, qualification, experience, eligibility, salary_min, salary_max, age_min, age_max, application_fee, vacancies, last_date, is_featured, description, apply_link) VALUES
('Staff Selection Commission - Combined Graduate Level (SSC CGL) 2024', 'Staff Selection Commission', 'All India', 'Bachelor''s Degree from recognized university', '0-3 years', 'Indian Citizen with valid ID', 25000, 150000, 18, 32, 100, 17727, '2025-01-15', true, 'SSC CGL is one of the most sought-after exams for government jobs in India. It offers positions in various ministries, departments, and organizations under the Government of India including Income Tax Officer, Auditor, Inspector, and more.', 'https://ssc.nic.in'),
('Indian Railways - RRB NTPC Graduate Posts', 'Railway Recruitment Board', 'All India', 'Bachelor''s Degree in any discipline', '0-2 years', 'Indian National', 35400, 112400, 18, 33, 500, 35281, '2025-02-28', true, 'Railway NTPC recruitment for various graduate level posts including Station Master, Goods Guard, Traffic Assistant, and Commercial Apprentice. Excellent career growth opportunities.', 'https://indianrailways.gov.in'),
('UPSC Civil Services Examination 2025', 'Union Public Service Commission', 'All India', 'Bachelor''s Degree from recognized university', '0 years', 'Indian Citizen', 56100, 250000, 21, 32, 100, 1056, '2025-03-20', true, 'The Civil Services Examination is conducted for recruitment to Indian Administrative Service (IAS), Indian Foreign Service (IFS), Indian Police Service (IPS) and other Group A and B services.', 'https://upsc.gov.in'),
('IBPS PO - Probationary Officer 2025', 'Institute of Banking Personnel Selection', 'All India', 'Bachelor''s Degree with 60% marks', '0 years', 'Indian Citizen aged 20-30', 52000, 85000, 20, 30, 850, 4000, '2025-01-31', false, 'IBPS PO recruitment for Probationary Officers in various public sector banks. Great opportunity for commerce and management graduates.', 'https://ibps.in'),
('Delhi Police Constable Recruitment 2025', 'Delhi Police', 'Delhi NCR', '12th Pass from recognized board', '0 years', 'Indian Citizen', 21700, 69100, 18, 25, 250, 5846, '2025-02-15', false, 'Delhi Police is recruiting constables for maintaining law and order in the national capital. Physical fitness test required.', 'https://delhipolice.gov.in'),
('DRDO Scientist/Engineer ''B'' 2025', 'Defence Research & Development Organisation', 'Multiple Locations', 'B.E/B.Tech in relevant discipline', '0-2 years', 'Indian Citizen', 56100, 177500, 21, 28, 100, 1500, '2025-03-10', true, 'DRDO is recruiting scientists and engineers for cutting-edge defence research projects. Opportunity to work on national security initiatives.', 'https://drdo.gov.in'),
('State Bank of India - PO Recruitment', 'State Bank of India', 'All India', 'Bachelor''s Degree from recognized university', '0 years', 'Indian Citizen', 48000, 78000, 21, 30, 750, 2000, '2025-01-20', false, 'SBI PO recruitment for Probationary Officers. One of the most prestigious banking jobs with excellent career prospects.', 'https://sbi.co.in'),
('Indian Army - Technical Entry Scheme', 'Indian Army', 'All India', '10+2 with Physics, Chemistry, Mathematics', '0 years', 'Unmarried Male Indian Citizen', 56100, 177500, 16, 19, 0, 90, '2025-02-28', false, 'Join Indian Army as a commissioned officer through Technical Entry Scheme. 4-year training at premier institutions.', 'https://joinindianarmy.nic.in'),
('EPFO Assistant 2025', 'Employees Provident Fund Organisation', 'All India', 'Bachelor''s Degree from recognized university', '0 years', 'Indian Citizen', 36000, 112400, 20, 27, 500, 2859, '2025-02-10', false, 'EPFO is recruiting assistants for managing provident fund operations. Stable government job with excellent benefits.', 'https://epfindia.gov.in'),
('NTA UGC NET June 2025', 'National Testing Agency', 'All India', 'Master''s Degree with 55% marks', '0 years', 'Indian Citizen', 57700, 182400, 18, 65, 1100, 500, '2025-03-31', true, 'UGC NET determines eligibility for Assistant Professor and Junior Research Fellowship in Indian universities and colleges.', 'https://ugcnet.nta.nic.in');